### ISSUE TITLE
Specify background color with jpg export

### ISSUE THREAD

**Issue by Frozenfire92** [shakiba/svgexport#10]
By default I seem to be getting black and can't find a way to change this from within the svg

**Comment by shakiba** [comment]
Yes, it seems phantomjs set the default background to black and I don't remember any way to set svg background.  I guess we should add a new param to svgexport to set page background or even better an option to inject css styles.

**Comment by Sjors** [comment]
It would indeed be nice if I can change the background color. In particular for PNG exports I'd like to make the background transparent.

**Comment by shakiba** [comment]
@Frozenfire92 @Sjors Just published a new update where you can pass styles to be injected into SVG document, for example:
```
svgexport input.svg output.jpg "svg { background: silver; }"
```
I'm not sure how robust this solution is, please try it and let me know if there is any issue.
