### ISSUE TITLE
Error on install because of puppeteer issue (with fix)

### ISSUE THREAD

**Issue by a-rousseau** [shakiba/svgexport#107]
There was an error installing because of the puppeteer dependency issue
https://github.com/puppeteer/puppeteer/issues/367

The fix is to do sudo install as follow
`sudo npm install -g svgexport --unsafe-perm=true`

Hope this will help others

**Comment by shakiba** [comment]
Thanks, would you be able to add it to the readme?

**Comment by a-rousseau** [comment]
You are right, will do !

**Comment by shakiba** [comment]
Thanks, merged it!

**Comment by a-rousseau** [comment]
my pleasure ! :)
