### ISSUE TITLE
problems with certain filenames

### ISSUE THREAD

**Issue by loominade** [shakiba/svgexport#14]
I cannot convert files with emoji in filenames:
```terminal
$ svgexport 📖.svg 📖.png
Error: Unable to load file (fail): path/📖.svg
```

**Comment by shakiba** [comment]
The issue is with phantomjs, but it is more than just emoji charachters. Currently I don't have enough time to fully investigate it and report it to phantomjs, so please either report it to phantomjs or temporary do not use special characters in your file names.

**Comment by loominade** [comment]
I'd like to, but I don't know what to tell them. What do you think I should report to [phantomjs](https://github.com/ariya/phantomjs/issues)?

Can't it operate with those filenames at all?

**Comment by shakiba** [comment]
I [reported](/ariya/phantomjs/issues/13633) it.

**Comment by davemackintosh** [comment]
It also doesn't like spaces in the path name, regardless of whether you escape them or not.

**Comment by shakiba** [comment]
@davemackintosh It may be an svgexport issue, can I see your example?

**Comment by davemackintosh** [comment]
I'm using it in an electron app on OS X, it's reading from the "Application Support" directory but says it can't find "Application " so I tried .replace(/\s+/g, "\\ ") but still no go.

**Comment by shakiba** [comment]
@davemackintosh Are you using svgexport as a node.js module? If so, please use arrays for output value, [see here](https://github.com/shakiba/svgexport/issues/24#issuecomment-153805985). I should add it to readme.

**Comment by shakiba** [comment]
@loominade I'm closing this issue, because it is a phantomjs issue. Hopefully in future versions of phantomjs it will be resolved.
