### ISSUE TITLE
Getting "TypeError: 'undefined' is not a function (evaluating 'el .getBBox()')"

### ISSUE THREAD

**Issue by goosehub** [shakiba/svgexport#16]
I've tried this with several inputs, and several options, but can not avoid getting this error. I bring it up here because I believe it may be an issue that could apply to more people than just me.

Installation went as expected, I'm familiar with nodejs and CLI, the command `svgexport` works as expected.

Example command (I've used several from the README, but here's just one command I tried)

`svgexport input.svg output.png`

Response

    TypeError: 'undefined' is not a function (evaluating 'el .getBBox()')

    TypeError: 'null' is not an object (evaluating 'input.width')
      phantomjs://webpage.evaluate():11
      phantomjs://webpage.evaluate():19
      phantomjs://webpage.evaluate():19

I've tried altering height and width in the svg, as well as other tags and attributes, but no progress. This is using Windows 7. If you need any additional information, let me know.

**Comment by goosehub** [comment]
Closing this issue. `<?xml version="1.0" encoding="UTF-8"?>` is required to be at the top. Perhaps this project can append this to the top of the svg if missing to avoid this issue all together? If I decide to use this in my project, I may make this change and do a pull request, but either way, closing this issue now.

**Comment by shakiba** [comment]
It may be resolved in phantomjs 2.0.

**Comment by jcklpe** [comment]
@goosehub @shakiba  Did you ever find a way to account for this problem programmatically?
