### ISSUE TITLE
Got blank PNG when convert some SVG to PNG.

### ISSUE THREAD

**Issue by sarunw** [shakiba/svgexport#19]
Here is the problem file https://dl.dropboxusercontent.com/u/2271974/egg.svg

**Comment by shakiba** [comment]
An immediate fix is to use `px` with viewbox values or just remove viewbox, but I will dig deeper to find the actual issue.

**Comment by sarunw** [comment]
You mean viewBox="0 0 96 96" to viewBox="0px 0px 96px 96px" ? Don't seem to work this way.

I upload and use web interface on the same file and it work perfectly https://iconverticons.com/online/

**Comment by shakiba** [comment]
My last suggestion was wrong, sorry. I'm working on it, but I can not consistently reproduce the issue which makes it very hard fix.

**Comment by shakiba** [comment]
A quick temporary fix for your case is to add `width="96" height="96"` to you svg element.

**Comment by shakiba** [comment]
I just found the issue, I'm working on fixing it.

**Comment by shakiba** [comment]
I have published an update to fix this issue, please try it an reopen this issue if still required.

**Comment by theogravity** [comment]
A bit late, but it seems to work! Thanks!
