### ISSUE TITLE
vector graphic?

### ISSUE THREAD

**Issue by rolfn** [shakiba/svgexport#2]
Shouldn't a pdf output file contain vector graphics? I tried the following example
```
svgexport NewTux.svg NewTux.pdf
```
The file "NewTux.svg" comes from http://upload.wikimedia.org/wikipedia/commons/b/b0/NewTux.svg The resulting pdf file contains bitmaps. This is bad.

And another issue: Without an explicit size parameter  the output pdf file ("NewTux.pdf") has two pages and the "penguin" is broken. It would be better if the pdf file has the same size as the (one page) svg file.

...Rolf

**Comment by shakiba** [comment]
I have dropped the support for PDF, because the PDF was just a wrapper around an image and not an actual SVG to PDF conversion. I think better results can be achieved with other package.
