### ISSUE TITLE
Rendering SVG with images fails if scaling too high (image gone)

### ISSUE THREAD

**Issue by RedRoosterMobile** [shakiba/svgexport#20]
Hi,

I have the following svg:

https://www.wetransfer.com/downloads/430cac04e6675d4bcd9ae85e4ac8b4e720150827150308/d18c71

it contains a relatively big base64-encoded image

I call the svgexport like that:

this works:
svgexport city.svg city.png 2.36x

![city](https://cloud.githubusercontent.com/assets/4501195/9524252/4141bb14-4cde-11e5-9961-206fa50fde52.png)

this (and higher scale) does not work:
svgexport city.svg city.png 2.37x

![city2 37](https://cloud.githubusercontent.com/assets/4501195/9524359/d5eb0522-4cde-11e5-9f14-23a1df6e0490.png)

in the last call the image is gone, but everything else renders perfectly.

This upper limit varies depending on the image included. The bigger the image the earlier the upper limit is hit.

Any hints on how to debug this, or where to look, where to increase memory limits?

**Comment by shakiba** [comment]
I really have no idea. I think this is too much load for this tiny library! You may want to try other libraries such as imagemagic's convert command.

**Comment by RedRoosterMobile** [comment]
I figured out a way:

just link the image from harddisk, than it works up to 16x!

file:///Users/mojomacssd/rails/marcel/covergenerator/svgs/SW_DominikMartin.jpg

**Comment by RedRoosterMobile** [comment]
found a way to circumvent this. instead of base64ing the images, just save 'em and use file:// protocol

**Comment by shakiba** [comment]
I'm glad to hear that! :)

**Comment by RedRoosterMobile** [comment]
btw, I tried probably all other libraries and they are all shit (batik,imagick,rsvg, cairo, ..).
Yours is, by far, the best! Thank you for that!

**Comment by shakiba** [comment]
Thanks, and thanks for sharing the issue and solution!
