### ISSUE TITLE
Viewbox can be wrong when specifying HD dimentions.

### ISSUE THREAD

**Issue by roipoussiere** [shakiba/svgexport#22]
On several vectors, the output picture is not on the good dimensions when I specify the width and / or height.

The tested image come from the official w3c svg test suite: [full-color-prop-03-t](http://www.w3.org/Graphics/SVG/Test/20061213/htmlObjectHarness/full-color-prop-03-t.html)

__Works fine without parameters__

    svgexport ./color-prop-03-t.svg out.png
    [...]/color-prop-03-t.svg [...]/out.png png 100% 1x 0:0:400:300 400:300

__Works fine when setting lower definition__

    svgexport ./color-prop-03-t.svg out.png pad 200:150
    [...]/color-prop-03-t.svg [...]/out.png png 100% 0.5x 0:0:400:300 200:150

![out](https://cloud.githubusercontent.com/assets/1665542/10430410/54c33588-70ff-11e5-83b5-b9b1ea084df7.png)

__Problem when setting higher definition__
Note it's the same aspect ratio and the `pad` option is enabled: __got a zoom of the original image__.

    svgexport ./color-prop-03-t.svg out.png pad 800:600
    [...]/color-prop-03-t.svg [...]/out.png png 100% 2x 0:0:400:300 800:600

![out](https://cloud.githubusercontent.com/assets/1665542/10430142/dc1c21e0-70fd-11e5-9a92-6f32a81257fe.png)

**Comment by shakiba** [comment]
I can reproduce the issue, but speechifying svg width/height in % makes sizing very [complicated](https://wiki.mozilla.org/SVG:Sizing). The best solution at this moment is to avoid them.

**Comment by shakiba** [comment]
I have published a new update which ignores % width/height, please try it and feel to reopen this issue if required.

**Comment by roipoussiere** [comment]
Ok, it works with this last update.
Thanks!
