### ISSUE TITLE
background black when converting to jpg

### ISSUE THREAD

**Issue by andreborud** [shakiba/svgexport#24]
maybe I'm doing it wrong but the css styling doesn't seem to work when not using cammandline. 

```
svgexport.render({input: imageUri, output: randomName + ' ' + size + ':' + size + ' 70%'}, function(){
	var img = fs.readFileSync(randomName);
	res.writeHead(200, {'Content-Type': 'image/jpg' });
	res.end(img, 'binary');
});
```
Code above and below gets a black background as a result
```
svgexport.render({input: imageUri, output: randomName + ' ' + size + ':' + size + ' 70% "svg{background:red;}"'}, function(){
	var img = fs.readFileSync(randomName);
	res.writeHead(200, {'Content-Type': 'image/jpg' });
	res.end(img, 'binary');
});
```

Any ideas?

**Comment by shakiba** [comment]
Have you tried using array for output instead of string?
```js
output : [[randomName, size + ':' + size, '70%', 'svg{background:red;}']]
```

**Comment by andreborud** [comment]
Nope, problem remains. :(

**Comment by shakiba** [comment]
Can you please share your svg file?

**Comment by andreborud** [comment]
Sure no problem, this is one of them: (Upload of svg isn't supported apparently)

```<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg width="100%" height="100%" viewBox="0 0 417 417" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:1.41421;"><use xlink:href="#_Image1" x="34" y="34" width="349px" height="349px"/><defs><image id="_Image1" width="349px" height="349px" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAV0AAAFdCAYAAACgiL63AAAACXBIWXMAAA7EAAAOxAGVKw4bAAAgAElEQVR4nO3dd7RlRZ328W/tKkAyLSoqQREMIKISREQJKogDKqIg+jqDaVDH7MgkXc4yzjAGjOiMjhkMgOgoJoJEUQQkiwISBUGyBBuqTr1/7NP5dt8T9j6/HZ7PWne13X3POY/Nvc+tU7t2lUPEmHfBA2sDaw1/netj0d954H5g4fDj/uV+XTjC392fcsyz+X8nsixnHUC6y7vwSOCJwNbAFsCDgQ3m+Fh7xtEycBNwxVwfKcc7Z5xHekSlK1PzLmxKWaxbs6Rkt6Is1Da6BbiSuQv5Fstg0n4qXRmJd8EBm7FssS4q1/UMo83aHZSFfCVwIXA68KuU40LTVNIaKl2Zk3dhHWB3YE9gZ8pyXccyU4P9FTgbOBU4DfhFyvFe20jSVCpdARZfzNqBsmQXFe1qpqHa6wHgXJaU8Bkpx7tsI0lTqHR7zLuwObAXZck+G1hgm6izEnABZQGfCpyecrzVNpJYUen2iHdhfeA5LBnNbmGbqLcycAllAf8AODHlmGwjyayodDvOu7Az8HzKkt2Rcp2rNMtNwNHAUSnHs6zDSL1Uuh3kXdgEeNXwQ6PZdvkD8C3gyJTjpdZhpHoq3Y7wLqwB7Ae8BnguUNgmkgpcCBwFfDPleK11GKmGSrflvAvbA68GXoEuhHVVBs6kLODv6CJcu6l0W8i78BDglZRlu61xHJmtB4ATKAv4eynHe4zzyJhUui0xXEe7N+X0wb7A6raJpAHuAb4OfDTleKV1GBmNSrfhvAuPBV4L/B3wCOM40kwJOBb4z5Tjb6zDyKqpdBvKu7AV8F7gQHRRTEZ3AnBYyvEk6yAyN5Vuw3gXtqYs2wNQ2crkzgEOA76bchxYh5ElVLoN4V14ImXZvhSVrVTncuCjwFe1E1ozqHSNDcv23ynLVv89pC5/Aj4JfE6btNvSN7kR78I2lGX7EvTfQWbnLuDzwCdSjjdah+kjfbPPmHfhSZRluz/69xc7C4EvAO9NOd5uHaZP9E0/I96FbSnL9sXo312a4xbg3cAXdcFtNvTNX7Ph5jMfR3O20mznAm/RLmf10zZ/NfEuFIUr3kq5aP2pqHCl2R4JvKZwxWMKV/wyM7jbOlBXqXRr4F3YDvg+5S27axjHERmVA54MHFK44oHCFedkBppyqJhGXxXyLqwNfAB4K/qBJu13GfDWlOMJ1kG6RKVbEe/CC4DPUB5TLtIlxwHvTDlebR2kC1S6U/IubAx8mnJVgkhX3Qf8F+W+DvdZh2kzle6EvAsF8CbgQ8C6xnFEZuUa4B0px+Osg7SVSncC3oWnAP9DedCjSB99HfiHlKNWOYxJpTuG4YWy9wNvQxfKRC4HXp5yPNc6SJuoOEbkXXg6cDLlcebaBUwENgReVbjivuHaXus8raCR7gi8C28BPgasZp1FpKF+AhyccrzZOkjTqXRXwbuwDvBF4GXWWURa4Cbg71KOP7MO0mSaXliJ4QkOJwK7G0cRaYt1gFcWrlincMUpupttbhrpzsG78ArK1QlrW2cRaalfA69IOV5hHaRpdEFoKd6F1b0LnwWORIUrMo0dgfO8C6+0DtI0GukOeRc2A44GnmadRaRjvgG8UWt6SypdwLuwN+UXxobWWUQ66grggJTj+dZBrPV6esG7UHgX3gccjwpXpE5bAqcPBzi91tvVC96FhwDfpdzzViN+kfqtDhxUuOL6zKC3I95elq534cnAqcB21llEeqYAXlS4gszgVOswFnpXut6FXYATgIdZZxHpsd0LV2xSuOLHfVvP26u31cP5pGOBtayziAgAPwIOTDneYx1kVnpTut6FAylXKGj/BJFmOQfYpy/7NvRi9YJ34XXAN1HhijTRDsBZ3oXHWQeZhc6XrnfhUOAL9OD/q0iLPQb4hXdhZ+sgdet0EXkXPkx5rpOINN+GwEnehf2sg9Spk6sXvAuucMURwDuss4jIWFYDDixccUtm8GvrMHXoXOl6FwLl+U2vsc4iIhNxwD6FK9bMDE60DlO1TpWud2FNyrvMXmKdRUSm9szCFatlBidbB6lSZ0rXu7Ae5Zq/Pa2ziEhldi1ccXdmcJZ1kKp0onS9CxtSnvLQ+SufIj2013C/ht9YB6lC60vXu7AW5W29O1pnEZHa7Fu44tLM4FLrINNq9ZIx74IHvo02HhfpugI40rvwPOsg02p16QJHAPtahxCRmVgd+K534RnWQabR2tL1LrwHOMQ6h4jM1FrA8cPtWVuplRveeBcOBr5inUNEzNwEPCvleLl1kHG1rnS9C3tSHq+jzWtE+u0a4Jkpx+utg4yjVaXrXXgKcBqwrnUWEWmEyyhHvLdYBxlVa0rXu/Ao4CzgEdZZRKRRzgWenXK8yzrIKFpxIc27sAD4MSpcEVnR9sAPhtsANF7jb47wLqxBeXvv9tZZRKSxHgVsmhl8zzrIfBpdut4FR3niw/Ots4hI4z25cMWNmcG51kFWpdFzut6Fw4G3W+cQkdZYCOyScmxs8Ta2dL0Lb6S840xEZBxXA9ulHG+3DjKXRpaud2Fb4GxgDessItJKxwMvSDlm6yDLa9yc7nDXsJ8BD7fOIiKt9Tjg/szgdOsgy2tc6Q7PNmv9TkJSqXuBW4E/AtcNf58pN0BpxbJHMbF74YozMoOrrIMsrVHTC96FA4DvWOeQmbgTuAA4H/j98PeLPu5a+teUY1zZk3gX1gEWABss9bGy3z8KeALQivWcUombgaemHG+wDrJIY0p3eMfZ+ZTfHNIdmfLCxvksKdkLUo5XW4TxLhTAY4AnLvWxzfDXxr3zk0qcAeyxqh/es9SI0h2e4Hsq0Op9MmWxSyg3lz+FsmAbf3umd2Fd4JnAbsOPHYBgGkqq9PGU4z9ah4DmlO4HgXdb55Cp/J6yaL+dcrzEOsy0vAtrUw4Cngu8lHJ0LO320pTjsdYhzEvXu7A7cBK6INJGV7GkaM+3DlMn78L2wIHAAcDmxnFkMncBO1jvwWtausNTfC8ANrbMIWNZCHwB+FrK8dfWYSx4F3YADgJeBWxom0bGdBHw9JTjvVYBTC8cFK74FjrFty0S5WkdL0k5fiszaMzV4FnLDG7IDH5WuOLTlBcJNwc2sk0lI9oIWJAZ/MgqgNlI17vwZuDTVq8vY/ku8O6U42XWQZrKu7AH8FbghWiqrOkGlPsz/NLixU1Kd3ib76+AB1m8vozsJOBf+zqNMAnvwmOBD1LO/0pzXUS5P8PMl5HNfHphuNHwCWhD8ib7NXBwyvF9fZ5GmERmcFtmcEzhih8BjwUebRxJ5rYRcG9mcOasX9jibdB7gK0MXlfm9wDwLmCnlONJ1mHaLOX465TjHsA+lKMqaZ73ehdmvhJlptML3oUtKBfOa/ew5rkKOCjleLZ1kK4Z3gX3NuBD6BbkpvlJynGmhyTMdHqhcMXXgK1n+ZoykmOAfVKOf7AO0kWZQc4Mflm44mjKO902tc4ki21ZuOKyzGBmN/TMbKTrXfgbyj0upTkWAu9MOWqz+BkZjnrfQXmxTReSm+FPwFYpxztm8WIzGel6F1YH/g8tJG+SGyiPrf6BdZA+GY56zypccQzlXg/aN9reOpRrd384ixeb1YW0d1JeyZVmuBbYteu37jZZyvF3wC5oK9OmOMS7sPMsXqj26QXvwsbA74C1634tGclVlNvcXWMdRErehfcA76cBe6H03MWUa3cfqPNFap9eKFzx38B2db+OjORyYPeU43XWQWSJzOC0whUXAPtSnoYhNh5GuXb3jDpfpNafrN6FXSn3yRV7l1HO4d5oHUTm5l3YhvLGIc3z2rkPeGLKsbYjfmqb0/UueLS3QlP8DthNhdtsKceLgT2B26yz9NiawOfqfIE6L6S9Adi2xueX0dwNvDjleLN1EJnfsHj3Bv5inaXHnuddeEldT17L9IJ34SGUJwksqOP5ZSwvSznqCnnLDKfmfoLuYLNyCfCklGOu+onrGul+CBVuExyuwm2nlONpwIsp98OQ2Xsi5TFNlat8pOtd2I5ylyrtKWrrdMoLZ404AVUm4114F/AR6xw9dTGwbdWj3cqXjBWu+CY6Q8ran4A923AKr6xa4YqzgKcDW1pn6aGHAZdkBpdW+aSVjnS9C88AZr4/pazgOSnHk61DSDW8CxtRniWoI4Fmr/LRbtVTAP9c8fPJ+L6jwu2WlONNwMFA5Rd1ZF7bAJWuZKhspOtd2Jryp4JuZbRzH/CElOO11kGket6Fj1PuUCazdRHw5KpGu1WOdA9FhWvtMBVup/078GfrED30JGD/qp6skpL0LmwC/AFYrYrnk4lcSznKvc86iNTHu/AW4FPWOXroQuApVYx2qxrpvhMVrrVDVbi98HngCusQPbQt5brpqU090vUuLKAcZa0zfRyZ0Gkpx92sQ8hseBcOQPvwWrgAeOq0o90qRrpvQoVr7YPWAWR2Uo5HAzpAdPaeDOw37ZNMNdL1LqwJXAM8dNogMrHLgK3ruEdcmkujXTPnU250PvH327Qj3degwrV2RB8Ld3jAY599H61ksPAU4EXTPMHEI93hfrmXo1t+Lf0F2Djl2LltAL0LmwF/Azya8nbMpT8eCqxF+f//Vsr9Z5f+9Qrg58AFXf6B5F34GOVFbJmt81KO20/64GlK9+XAUZM+XipxRMrxTdYhquJdWDRnth/liGJat1CeXHIycGLK8fcVPGdjeBe2AirdF0BGtn3K8bxJHjhN6Z5PObEsdrZOOf7WOsS0vAuvA/6N+t81/QD415TjJTW/zsx4F84EnmGdo4c+m3J88yQPnGhezLuwNypcaye3vXC9C5t7F04EvsBspqleAFzoXfjKcPqiC75kHaCnXuFdWGOSB056MeLQCR8n1fmadYBJeRcK78LbKe9pf86MX76g3Dzm996F18/4tevwI+sAPbWACZePjT294F14NOUtv9pnwU4GHt7Gc8+8C4Hybf7e1lko/x0PSTl+0TrINLwLvwWeYJ2jh36achz763iSke7LUeFaO7eNhTv0OZpRuFB+Hf+Pd+Fg6yBT0laeNvYc7jszlklK9xUTPEaqdbx1gEkMj555nXWO5TjgS96Fqe80MnSSdYCeWjRVNZaxRqzehSdR7rYjtnZKObbqNtBhqR1Lc8/Ou4lyl7Y7rIOMy7vwYMobJZr6b9tlVwKPHWc9+Lj/kTTKtXcz5cGfreFdeBxwJM0uhY0oT7FunZTjbZS3p8rsbQE8a5wHjPxN4F1wwEHjJpLK/bSFd1kdRnkHWdO9wbuwg3WICekdqJ3XjPPJ44w8nkF5S6bYatUSIe/CM6lgZ6YZKYAjrENMqFN327XMS70LI++0OE7pamqhGc6wDjCq4bujj1nnGNOO3oVdrUNM4HLrAD22NnDgqJ88UukO11YeMGkiqcxtKcfrrUOM4UDgadYhJjDR7Z3GVLq2Rp5iGHWkuyfawrEJLrIOMKb3WQeY0Iu9C4+0DjEmHeFja5fhBeN5jVq6mlpohtZcLBnO5T7eOseEAnCIdYhxpBzvAW6wztFzrx7lk+Yt3eHpEG25ENJ1rSld4FXWAaa0r3WACVxlHaDnXjnKJ40y0n0hOgOtKVpRut6FtWj/NYCneBfWtQ4xps5tZt8ym3gXtpnvk0YpXU0tNMMAaMs+sPsD61mHmJKnffvU3m0dQNhzvk9YZekOj1dvyuYkffeH4bxdG7zMOkBF2rZ0TKVrb7rSpRyxrF5NFpnSxdYBxrCzdYCKbGcdYExt+aHcZbt5F1bZmfOV7vMqDCPTacWVae/CFsCG1jkq8hDrAGPSSNfeWsAuq/qE+Uq3bW+vuqwt++fuZB2gQm374aHSbYZVTjGstHS9C4+n3HlJmqEtpdvGO9BWpm2l+1frAAJMWrpolNs0bSnd7a0DVGg978Jq1iHG0LYlbl21nXdhpT+wV1W6u9UQRibXltLt0rujCCTrEGNo+zK9rihYxYGrGum2R1tKd4F1gAr9KeU4sA4xhvWtA8hiK51imLN0vQubA5vWFkcm0ZbS3cA6QIX+aB1gTBrpNsd4pYtGuU3zQMrxdusQ8/EurEe5WUxXtG27RI10m+NRK9t1TKXbDn+2DjCiLo1yAX5oHWBMKt1mmXO0u7LS1UW0ZlloHWBEa1gHqND9wI+tQ4xJ0wvNMmfprvBWcLh58xa1x5FxPMi7sLt1iBFsbB2gQqekHO+yDjEq78LawGOsc8gy9vAuhJRjXPoP55p/0yi3eR4B/Nw6RM98zjrAmHYG2rSmuA/Wo7xD88yl/3Cu6QXN50rfXQh83zrEmPR920wrbP40V+lqpCt998GUY7YOMSaVbjM9cfk/cEv/xrvwUNqzHlSkDpcCT2rTTRHDrQTvBB5knUVWcHbKcZlNoJYf6eqnpfTdW9pUuENPQ4XbVFst/wfLl27bjicRqdJXU44nW4eYgAZLzbWud2Gzpf9g+dJ9wgzDiDTJn4F/tA4xoX2sA8gqbb30b5Yv3S1nGESkSd6ZcrzVOsS4vAvboXeoTTd36XoXCuDRs04j0gBfTzl+wzrEhN5mHUDmtdKR7mboEErpnzOA11mHmIR3YSPgIOscMq9llo0tXbqaWpC+uRJ4ccrxfusgE3oDGii1wTIrGFS60le3A/umHG+xDjKJ4drcN1jnkJGs711YvC+JSlf66CrgGSnHy6yDTOFA4OHWIWRki6cYVLrSN2cBO7W5cIcXvd9pnUPGsvhimkpX+uQ7wLNTjm3ZFH5l3gg81TqEjGXZ0vUuOLQXp3TX/cC/AgelHP9qHWYa3oVNgP+wziFjW1y6i/bTfSSwpk0WkVpdBPxtyvEC6yAVOQJY1zqEjG2F6QVNLUjXDICPADt2pXC9CwcAL7DOIRNZ4F14BCwZ6ap0pUuuAg5OOZ5uHaQq3oUNgE9Z55CpbAncqJGudM0XgW27VLhDH0FLxNpuAWikK91xE/C6lGPbjk2fl3fhucBrrXPI1DYAzelKNxwLbNPRwn0c5VI3N9/nSuNtAEtGulouJm10J+VJD1+3DlIH78KDgR8yfFsqrVeWrnfBUx4VLNImpwP/L+V4nXWQOngXVqMcwT/WOotUZvH0gnYpkrb5JOWdZV0tXA98CdjdOIpUa/H0whrGQURGdS/w9ynHo6yD1GW4e9hRwEuss0jlVLrSKn+g3Pv2QusgdfEurA0cB+xpnUVqsXh6QaUrTfdjYIeOF+4C4ERUuF2m0pXGy8AHKDcbv906TF2Gt4eeCjzdOovUavH0gi6kSRPdSblRzQ+sg9TJu7AT5SqFjef7XGk9jXSlsS4BntaDwn0t5QhXhdsP64FGutI8JwD7pxzvtg5Sl+Ea3E9SbkYu/eG9C6tp9YI0yfHAS1KOC62D1GV4bPoxwDOts4iJ1TS9IE1xHOUIt8uF+zTgXFS4fba6Slea4NvAgSnH+62D1MW78BrgNDR/23er6TZgsfY1yj0UonWQOngXVvMufBb4XzTAEVhdc7pi6QvAG1KOA+sgdRjO3x4NPMs6izSG0/SCWPkM8PoOF+6OwDmocGVZSaUrFj6WcnxLyjFbB6mDd+HVlFtPbmKdRRonanpBZu3wlOO7rEPUwbuwPuX624Ots0hjpcCS0yNE6nYKcKh1iDp4F/aivFim0a2sSiqAzq6LlEa5ETgo5Zisg1TJu7COd+HzwE9R4cr8YgDusU4hvfCmlONN1iGq5F3YFfgKsLlxFGmPVKDSlfqdmXI8zjpEVbwLD/IuHE45XaLClXFopCsz0Zl53OFWjF8FHm+dRVpJI12p3QUpx7OsQ0zLu7C6d+HDwJmocGUyD6Qcc6A87E+kLt+3DjAt78LDgR8BT7XOIq12L5TLxTTSlTr9n3WAaXgXHkV5dtmW1lmk9e6F8uQIla7U5fqU47nWISblXXg8cAYqXKmGSldq19pRrnfhqehWXqmWSldq18rS9S7sAvwceKh1FumUxaV7H9DJnZ7EVKIsrlbxLjwP+BmwvnUW6Zz7AIrhTk93GYeR7rmxbSdBeBf2pxydr2WdRTpp8UgX4A7DINJN11oHGId3YRvgSHSSitRHpSu1ak3pehfWAI4CHmSdRTrtBlDpSn1aU7rAYcCTrENI510BKl2pTytK17vwWOCt1jmkF1S6UqtWlC7wZsBZh5BeWKZ0bzYMIt3U+NL1LqwLvMo6h/RCBK6GJaV7mVkU6ao2/CB/MbCedQjphWtTjg/AktK91DCMdFMbdq97vnUA6Y0rFv0Pla7UpdGl610ogD2tc0hvLFu6Kce/ANeZxZGuiYveSjXYDsCG1iGkN1YY6YJGu1KdRo9yh3axDiC9MmfpXmIQRLqpDaW7wDqA9IpGulKrNpTuOtYBpDcGwB8W/UalK3VQ6YoscX3KceGi36h0pQ5tKN11rQNIb1y59G8Wl27K8U7gjzOPI110n3WAEWikK7NyxdK/KZb7S412pQrZOsAINNKVWVHpiqDNymV2Vlm6WjYmfaGdxWRWLlr6N2G5v9RIV6qwu3ehDVMMInW7MeV4+dJ/oOkFEZH6nLb8HyxTuinH24EbZxZHRKTbVl26QxfN8WciIjK+kUr31BkEERHpuluZY3HCXKX7s/qziIh03ukpxxUuKM9VuucBt9WfR0Sk0+acNVihdFOOA+Ck2uOIiHTbCvO5MPdIF+CEGoOIiHTdXcD5c/3FykpX87oiIpM7YzhrsII5SzfleA1w+Vx/JyIi85pzagFWPtIFTTGIiExqotLVFIOIyPjuBc5Z2V+uqnR/DsTK44iIdNtZKccHVvaXKy3dlONdwNm1RBIR6a6VTi3Aqke6oHldEZFxrXIrhflKV/O6IiKjuwU4c1WfMF/pnk25yFdEROZ3TMpxldfCVlm6wwf/vNJIIiLdddR8nzDfSBc0xSAiMoprgTPm+6RRSveHtONIbRERS9+cayvH5Y10Iqp34UTgOVNHEhlNptxe9KalPm4BPLAJsBmwKfBgq4Aic3hyyvHC+T5p+dOAV+bLqHSlXpcCPwF+TLn588L5HuBdWBt4FOXX5n7Aroz+NS1SpYtHKVwYfaS7JuWBletPk0pkOTcAHwW+O9xkaSrehQXAvsABw19H+voWqcC7U44fHuUTR/6i9C58Hnj9xJFElrgJ+E/g8ynHv9bxAt6F7SkLffc6nl9kOZunHK8e5RNHuZC2yJcmyyKy2P3AvwCPSTl+oq7CBUg5npty3AN4AeXUhUhdzhq1cGGM0k05ns0cJ1uKjOiPwK4px8NSjvfO6kVTjj8EtgU+OavXlN6Zd23u0vw4n1y4Yk1gr7HiiJQbgOyZcvydxYtnBjkz+EnhiluA5zHeOzyRVYnAazODe0Z9wLhffN9A2z3KeL4KPCfleJN1kJTjZ4EXAn+xziKdcVLK8eZxHjBW6Q6/cX40ViTps5OA1813L/ospRx/BOxJOb8sMq2xphZgzOkFgMIV9wEHjfs46Z3fAXvNcv52VJnBHwtX3ArsY51FWu0+yqmFsX6ATzK3dTzlkh+RlbkV2DfleId1kJVJOX4OONI6h7TaD1OOY09VjV26w7eK3xj3cdIrb0s5XmEdYgSHABdbh5DWOmKSB010x4534Ynoi1Xmdi6w4ygbfzSBd+GZwOnWOaR1zk457jTJAydaOpNyvASdnyZzO7QthQuQcjyDec60EpnDYZM+cJr1il+e4rHSTT9OObZx0/sPWgeQVvkd8L1JHzxN6R5Juf2eyCKtLK+U4wnAr6xzSGt8JOU4mPTBE5fu8Krd4ZM+XjrnBuAs6xBT+Lh1AGmFG4CvT/ME094O+Sng9imfQ7rh+22ay53DCcDEoxfpjU+kHKe6sWaq0k053oVGu1KaeI6rCVKOtwPnW+eQRrsD+Py0T1LFxh+fRKPdvruTbpwafbJ1AGm0z01yM8Typi7d4Wj3E9M+j7Tab1KOD1iHqIBKV1bmr1S0PWhVW9x9knLoLf10nXWAivzSOoA01ler2imvktJNOd6JRrt9dq11gIrcgS6myYoGlEc/VaLKzZw/gUa7fdWJ0h2uvrjTOoc0zrFV7iVSWekOR7s6EqWfOlG6Qxo4yPL+s8onq/rYkk+gkUIfdekkBq3EkaWdmHI8r8onrLR0h/unarTbPxtYB6iQBg2ytPdX/YR1HNB3OPrC7ZsHWweo0NrWAaQxvplyrHzbz8pLdzja/VTVzyuNtsA6QIW69ANEJncPcGgdT1zXUdSHA3fV9NzSPCpd6ZoPpRz/WMcT11K6w/vYK73iJ432cOsAVfAuOLo1Py2TuQL4WF1PXtdIF8rFxJfU+PzSHLtaB6jI+tT7PSHt8PZpdxJbldq+wIb34r8eaPN2fzKarb0Lj7AOUYEdrAOIueNTjsfX+QK1/lRPOZ4JfLHO15DGeK51gAo8zzqAmFoIvL3uF5nFW6l/AirZKEIaTaUrbffxKm/3XZmJjmAfl3fh5cBRs3gtMXMzsFnKcaF1kEl4Fx4J1HK1WlrheuAJKcd76n6hmVw0SDl+E/jpLF5LzDwMeK11iCnsax1ATB06i8KFGY10AbwLjwEuBtac1WvKzF0HbFnnld86eBcCcBmwhXUWMXFqynH3Wb2Yn9ULZQa3F65IdGPuT+a2PnBDZnCOdZBxFK54HfB31jnERAL2ywxmdt1pZiNdAO/CasB5wDazfF2ZqWuBx7Vlbte7sAblYvhNrLOIic+kHN8yyxec6ULw4drdQ9Da3S7bDPi0dYgxvAkVbl/9GXjvrF90ZtMLi2QG1xeueARaiN5l2xeuuC4z+I11kFXxLuwEfAMI1lnExEEpxwtn/aIznV5YxLuwAfBbOnLPvszpr8AuVW8AXRXvwibAr9HXYF99OuX4VosXNrnPfLj9Y+13foipBwHHDte/Nop3YU3ge6hw++oCatq2cRRmm3ukHL8N/J/V68tMPBo427vwVOsgi3gX1gWOBra3ziIm7qWcVjC70Gu9o9KrgKuMM0i9NgZO9y680DqId+HxwK+AfbeQBYQAAAhxSURBVKyziJm3phwvswxgWrrDfXcPoNxoQrprbeA478I/eRdmfvEWwLvwIuBsYCuL15dG+HbK8X+tQ5h8AywtM7ixcMWf0W2YXeeAPYH9C1dckxlcPosX9S5sWrjiI8B/Uc4zSz9dDeybGZgP8ExWL8zFu/A14G+tc8jMnAy8K+VYy7Ky4eqEf6PcD2L1Ol5DWiMCu6Ycz7IOAs0q3bUo59t0t1p/ZOB04DjguJTjNdM8mXdhbWAP4EWUP8DXmDqhdMF7Uo4fsg6xSGNKF8C78DjKtZPrWWcRE+dRFvAFlLcTXzuc91/B8PbdjYBHUB4XtDfwTDSqlWX9HHhuynFgHWSRRpUugHfhJcAx1jmkMf5CuXvZn4HVKLeQfBj6wSzzuwV4csrxBusgSzO/kLa8zOC3hSvWB3a2ziKNsAbwUMo1v5tSHpGuaQMZxctSjudah1he40a6sHh/01OAXYyjiEg7md3mO59Gli4sPj7lN5RvJUVERnUWsEdTtxe1viNtpYbzMC8HGjMBLiKN93vgBU0tXGjgnO7SMoOrhqdNPNs6i4g03k2UI9xGXThbXqNLF6BwxRnAdsDjrbOISGPdA+yVcrzUOsh8Gju9sEjKMQMHAb+wziIijRSBA1KOrTibr/GlC5ByvJdyZ6gLrLOISOO8MeX4Y+sQo2pF6cLijc+fB8xkoxQRaYX3pxy/aB1iHI1dMrYy3oVHAWegwwRF+u7LKcfXWIcYV+tKF8C78ATKjVIeYp1FREz8FNg35Ritg4yrlaUL4F3YnnJ7QN2DL9Iv5wG7pRzvtg4yidaWLoB3YTfgJ2hzapG+uBrYOeX4J+sgk2rNhbS5pBxPpTzup3VvMURkbLcBz29z4UILbo6YT2bw+8IVVwIvpuUjdxFZqfuAv6nrpJFZan3pAmQGFw3PWdMpryLdcxewT8rxDOsgVehE6QJkBucUrngAeI51FhGpzC2UJz/80jpIVTpTugCZwemFK9ZG+/CKdMH1lBvYXGQdpEqdKl2AzOCEwhUAuxtHEZHJXQ7snnK80jpI1TpXugCZwamFK66jnONt9QoNkR46H3h207donFSnr/Z7F/YGjgbWsc4iIiM5k/Ki2Z3WQerS6dIF8C5sBxwPPNw6i4is0k+B/Ye7CnZW5996pxzPozxZ+DLrLCKyUkcDL+x64UIPShcg5Xg15YqGM42jiMiKvggclHK83zrILPSidAFSjrcBzwW+a51FRBb7aMrx71OOvTmAtpOrF1YmM4iFK44BFgA7WecR6bl/Szm+1zrErPWqdAEyg5wZ/KRwxT3AnvTgYqJIw9wH/H3K8TPWQSz0unC8CwcBXwVWt84i0hNXAC9NOfb2vMNely6Ad2F34DhgA+MoIl13HPCqlONd1kEs9eZC2sqkHE8BdgB+bRxFpKsi8K6U4/59L1zo4ZzuXDKD2wtXfIXyBIpnoHcAIlW5EXhByvFb1kGaQuWyHO/CXsDXgI2ss4i03CmU629vsg7SJL2fXlheyvFnwLaUZ6+JyPgy8B+U++CqcJej6YU5ZAb3FK44CvgL5RaR+ncSGc0dwMtSjp/LDLJ1mCbS9MI8hke9fxN4rHUWkYY7j3I52FXWQZpM0wvzSDmeC2wHfN06i0iDfQF4hgp3fhrpjsG78ErgCGBd6ywiDXEr8LaU45HWQdpCpTsm78KWlNMNO1hnETH2NeAfU463WAdpE10gGlNmcNtSa3p3Rj+4pH9+DxyQcjw8M+j8/rdVU2FMYXgqxacpb6gQ6br7gcOAD6UcF1qHaSuV7pS8Cw54JfBf6Egg6a7TgNenHHUCy5Q0vTClzIDM4MLCFf8DrAbsiP5dpTtuA94MvF1zt9XQSLdi3oUnAJ8E9rLOIjKlr1NeKPuzdZAuUenWxLuwH/BxYHPrLCJjuhx4Y8rxJOsgXaS3wTXJDC4rXPHflBcfnk459SDSZPdT7pnwipTj5dZhukoj3RnwLmwGfAx4qXUWkTlk4FjgvSnH31qH6TqV7gx5F54DfArY2jqLCEvK9n0px4utw/SFSnfGvAsBOAQ4FHi0bRrpqQwcA7xfZTt7Kl0jw/I9EPhnyv17Reo2YEnZXmIdpq9Uug3gXXg+ZfnuZp1FOmkAHE1Ztpdah+k7lW6DeBd2Av4FeBH6byPTGwDfoSxbXSBrCH1jN9DwBotDKW8vXt04jrTPAPg28AGVbfOodBvMu7Ax8A7KC2/aw1fmEylHth/QHgnNpdJtAe/CBsA/AG8DHmYcR5rnEuDLwDd0EGTzqXRbxLvwIOBg4NXATsZxxNadlJvpfznleLZ1GBmdSrelvAtbAC8HXgFsZRxHZiMDJwNfAo5LOd5nnEcmoNLtAO/CUyjL9yBgU+M4Ur2rga8AX0k5XmMbRaal0u2Q4Ybqz6Is4JcCG9omkincR3mL7peBn6ccs3EeqYhKt6O8C6sBe1MW8AuBtWwTyQgy8CvKov1WyvEu4zxSA5VuD3gX1gb2oyzgvYBgm0iW8kfghOHHiSnHm43zSM1Uuj3jXdgQ2APYlfK24yehr4NZuhs4lbJkf6abF/pH32w9511YQDkPvOvwYzu0uX2VBsA5LBnN/iLl+IBtJLGk0pVleBfWAXZhyUh4R3Qr8riuYknJnpxyvM04jzSISldWybuwJuVxQ4tGwjsDa5qGapYbgEsp7wq7GDgl5XiFbSRpMpWujGW4KmI74PHAlst9LDCMVrfrKYv10qU/Uo53mKaS1lHpSmW8Cw+mLN8tWLGQ27BnRAauY9lyvQT4rZZvSVVUujIT3oV1WbaEtwAeTLl+eOmPNZf7fTHhSy4E7hjh487hrzcDv0s53j3h64mMRKUrjeZdKCjXFfvhR1ju1wJIlMeHP7Do15RjMgksMo//DwjnfEP3yxUxAAAAAElFTkSuQmCC"/></defs></svg>```

**Comment by shakiba** [comment]
Thanks for reporting, I had made a mistake in last update, I fixed it. Please update and try it again, and let me know if you still have any issue.
