### ISSUE TITLE
Scale does not work for SVGs using ex

### ISSUE THREAD

**Issue by szarnyasg** [shakiba/svgexport#25]
Hi, I came across this issue while using GitBook for converting MathJax to PDF (issue https://github.com/GitbookIO/gitbook/issues/853 is loosely related).

I created a minimal example for the problem: https://github.com/szarnyasg/svgexport-ex. The `ex` unit does not work well with svgexport's scale option. Exporting `circle1.svg` with scale 1x is okay (https://github.com/szarnyasg/svgexport-ex/blob/master/circle1-1x.png), but scale 2x crops the circle (https://github.com/szarnyasg/svgexport-ex/blob/master/circle1-2x.png crops). Similarly, MathJax SVGs are rendered incorrectly when scaled -- e.g. the text does not get scaled at all. In contrast, `circle2.svg` does not use ex and works correctly for both scales.

Do you plan to add support for `ex` units?

**Comment by shakiba** [comment]
I can reproduce the issue but I don't think this is a svgexport issue. Even in my browser circle1 is not rendered correctly:
![circle1](https://cloud.githubusercontent.com/assets/1061095/11165781/9221e508-8ae7-11e5-8bdf-5f0f2de90d33.png)

**Comment by szarnyasg** [comment]
Well, it's actually rendering it in Chrome, Firefox, Edge and Internet Explorer gives 4 different results... I'll look into the details later and see if specfying the font can help the browsers to render correctly. Still, scaling in svgexport should not crop the pic.

**Comment by shakiba** [comment]
svgexport does not crop the image, phantomjs does it, chrome also cropped it in above picture.

**Comment by shakiba** [comment]
@szarnyasg I'm closing this issue, please feel free to open it again if there is any update.
