### ISSUE TITLE
External fonts don't work - Upgrade to PhantomJS 2

### ISSUE THREAD

**Issue by davemackintosh** [shakiba/svgexport#27]
If you're using web fonts, from say Google Fonts they won't appear because there is no wait for resources to finish loading before rendering the image.

Is there any fix for this?

**Comment by shakiba** [comment]
Probably a page load listener should be added before rendering. If it is possible for you please check if you can fix it, otherwise I will try to add it as soon as I'm free.

**Comment by davemackintosh** [comment]
I'm looking to add support for the load event right now in a fork. Will submit a PR when done. 

https://github.com/newworldcode/svgexport
http://www.w3.org/TR/SVG11/interact.html#LoadEvent

**Comment by shakiba** [comment]
That's great, thanks!

**Comment by davemackintosh** [comment]
Well.. What a waste of time that was.. It just turns out that it doesn't support fonts very well.. Need to update to PhantomJS 2.0

http://stackoverflow.com/questions/23404658/how-can-i-use-google-web-fonts-with-phantomjs

**Comment by davemackintosh** [comment]
Working on an update.

**Comment by davemackintosh** [comment]
:boom: Got Phantom 2.0 working and fonts are fixed. Will be submitting a PR once the tests are fixed.

**Comment by davemackintosh** [comment]
@shakiba

**Comment by shakiba** [comment]
@davemackintosh Thanks, I have been resisting not to use phantomjs 2.0 for a while, but it seems that this time I can not! Please give me just few days.

**Comment by davemackintosh** [comment]
How come you've resisted updating?

**Comment by shakiba** [comment]
The main phantomjs npm package is not upgraded to v2 yet and [this issue](https://github.com/Medium/phantomjs/issues/288) is still open. I just checked the phantomjs2 npm package, it does not support Windows yet. I will use it in an alpha version, because otherwise svgexport won't be usable in Windows.

**Comment by davemackintosh** [comment]
Looks like that issue has been closed and updated, I think this PR is outdated now that 2.1 is out. I will revisit in the next few days to update the PR.

**Comment by shakiba** [comment]
@davemackintosh Thanks, I appreciate your help. It seems that the package name is also changed to phantomjs-prebuilt.
