### ISSUE TITLE
Stroke Attributes in svg

### ISSUE THREAD

**Issue by baierjak** [shakiba/svgexport#31]
I have troubles with exporting svg elements with attributes "stroke-linejoin" ... For example I have stroke-linejoin="round" but always it is ignored in export and it is the same result as stroke-linejoin="bevel" by default. Can I do something about it?

**Comment by baierjak** [comment]
This issue is almost only with TEXT elements

**Comment by shakiba** [comment]
Can you please share an example, it is probably a phantomjs issue.

**Comment by baierjak** [comment]
Yes, thats problem with phantomJS. Have you any experiences with other browsers?

**Comment by baierjak** [comment]
maybe you can see it in this example. in png you can see outline is not ROUND :)
[export.zip](https://github.com/shakiba/svgexport/files/268254/export.zip)

**Comment by shakiba** [comment]
I suggest that you try a simple shape, such as square, instead of text.

**Comment by baierjak** [comment]
Haha. Not so good solution. How can I change text for square? :)) But i have solution >> transform every single letter from text element into path element here we go :)!

**Comment by shakiba** [comment]
I meant check if the issue exists with a simple shape (path) such as square, as well. I was suspect that the issue is somehow related to fonts or text. Anyway, good to hear that you fixed it.

**Comment by baierjak** [comment]
Yes. This issue is only with text elements. Dont know why.
