### ISSUE TITLE
PNG/JPG to SVG

### ISSUE THREAD

**Issue by ThomasLohmann** [shakiba/svgexport#32]
Hi Ali,

first of all thanks for your good work. Is it also possible on your codebase to export PNG/JPG to SVG? Or do you see any other possibility to implement PNG/JPG to SVG, for example, with Node.js? It would just be the other way round. What I have found is this here: http://potrace.sourceforge.net/
But it is more for black & white graphics. With colours it would be perfect.

Best regards,
Thomas

**Comment by mitar** [comment]
That is a hard problem and in general not just a question of packaging something for node.

**Comment by shakiba** [comment]
Closing this, as not in scope of this project.
