### ISSUE TITLE
Updates to install instructions in Readme

### ISSUE THREAD

**Issue by xenotropic** [shakiba/svgexport#36]
Consider noting in Readme.md that "sudo apt-get install nodejs-legacy" is necessary on debian/ubuntu systems to use npm

http://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu

Also consider putting "sudo" before "npm install svgexport -g"

It'll save a bunch of people a few seconds and a few googles to install it correctly :^)

**Comment by shakiba** [comment]
I do not recommend using `sudo` for that! :)
