### ISSUE TITLE
SVG Export for Windows

### ISSUE THREAD

**Issue by spertasolutions** [shakiba/svgexport#44]
Can you please explain how can we use SVG Export on Windows, as an API or may be a stand-alone application.

**Comment by shakiba** [comment]
Please try:
- [Download](https://nodejs.org/en/download/) and install node.js+npm for Windows
- Run `npm` from command line to make sure it works
- Run `npm install svgexport -g` to install svgexport

**Comment by shakiba** [comment]
I'm closing this, please feel free to reopen if required.
