### ISSUE TITLE
Unable to load file when path contains `é` character

### ISSUE THREAD

**Issue by BenRKarl** [shakiba/svgexport#49]
When the `é` is present in the file path this error is generated:

```
Error: Unable to load file (fail): /fake-path/tést/syndication-logo.svg
```  
Removing that character remedies the problem.

**Comment by shakiba** [comment]
I think it was reported before, and it was a phantomjs issue.

**Comment by shakiba** [comment]
I'm closing this, please see #14 and feel free to reopen if required.
