### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by gqueruel** [shakiba/svgexport#51]
Hello,
I've tried to install svgexport but i have this error message :
`loadDep:uuid → resolveWit ▌ ╢█████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
/usr/local/bin/svgexport -> /usr/local/lib/node_modules/svgexport/bin/index.js

> phantomjs-prebuilt@2.1.16 install /usr/local/lib/node_modules/svgexport/node_modules/phantomjs-prebuilt
> node install.js

sh: 1: node: not found
/usr/local/lib
└── (empty)

npm ERR! Linux 4.10.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "svgexport" "-g"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gqueruel/Images/feather/npm-debug.log
npm ERR! code 1
`

**Comment by shakiba** [comment]
I can not reproduce, can you please test with another environment?

**Comment by shakiba** [comment]
I'm closing this, please feel free to reopen if required.
