### ISSUE TITLE
Unable to load file on Windows

### ISSUE THREAD

**Issue by jindrazak** [shakiba/svgexport#72]
### I am facing trouble exporting svg to png on Windows. 

- Windows 10
- Node v12.13.1 
- svgexport@0.4.0

### Way to reproduce:
Powershell:
```powershell
> npm i svgexport -g
... OK
> svgexport.cmd .\inputimage.svg outputimage.png
Error: Unable to load file (Error: net::ERR_INVALID_URL at file://C:%5CUsers%5Cjindr%5Cinputimage.svg): C:\Users\jindr\inputimage.svg
```

**Comment by jefago** [comment]
I have the same issue. Works with 0.3.2, stopped working with 0.4.0.

**Comment by jefago** [comment]
The problem is here: https://github.com/shakiba/svgexport/blob/master/render.js#L30

On Windows, `svgfile` will be something like `C:\users\....`, so the URL that gets created is `file://C:\users\...`, but it *should* be `file:///C:/users/` (three forward slashes, backslashes replaced by forward slashes although I'm not certain the latter is needed).

**Comment by MichaelHeerklotz** [comment]
Yes, I have already prepared a fix for Windows. There is still another Windows bug to be fixed, once this is done we can release a new version.

**Comment by roman-petrov** [comment]
@MichaelHeerklotz , any chance to make the latest version work on Windows soon? :)

**Comment by MichaelHeerklotz** [comment]
@roman-petrov I am aiming for a release this week. Sorry for taking so long.

**Comment by roman-petrov** [comment]
@MichaelHeerklotz , sounds great! Thank you!

**Comment by liuchaobit** [comment]
I have the same problem
where can I find the latest version

**Comment by ctch3ng** [comment]
For Windows users, in **%AppData%\npm\node_modules\svgexport\render.js**

Change the line

`await page.goto('file://' + encodeURI(svgfile))`

into

`await page.goto('file:///' + encodeURI(svgfile).replace(new RegExp(/%5C/g),"/"))`

**Comment by jindrazak** [comment]
@ctch3ng Wouldn't it be better to apply a pull reuquest?

**Comment by jamesmontalvo3** [comment]
Submitted #83. Resolved issues on Windows for me. Haven't tested on other systems.

**Comment by silverwind** [comment]
Alternative PR: https://github.com/shakiba/svgexport/pull/86

**Comment by FJEagle** [comment]
version 0.4.1/0.4.2 on win 10, error still happened. 
to merge PR: #86 ?

> Submitted #83. Resolved issues on Windows for me. Haven't tested on other systems.
