### ISSUE TITLE
Add option to change timeout for navigation

### ISSUE THREAD

**Issue by kylebarron** [shakiba/svgexport#73]
I'm trying to convert a 180MB svg to png. I tried with `svgexport` but got this error:
```
> svgexport test.svg test.png 4x "svg{background:white;}"
Error: Unable to load file (TimeoutError: Navigation timeout of 30000 ms exceeded): /Users/kyle/github/mapping/all-transit/svg/test.svg
```

It looks like that's from here:
https://github.com/shakiba/svgexport/blob/3acbf51f0687f54d1972265cd3aef4c6a7e925fc/render.js#L30-L34

It looks like you can easily modify the page timeout by setting `{timeout: ...}`:
https://stackoverflow.com/a/52163615/7319250

**Comment by shakiba** [comment]
Hmm, that makes sense, thanks of reporting the issue! Would you be able to make a PR for this?
I think the easiest way is using environment variables to pass timeout to svgexport.
