### ISSUE TITLE
Update to puppeteer 3.0.0

### ISSUE THREAD

**Issue by KasparEtter** [shakiba/svgexport#79]
I ran into a rendering issue: `marker-mid` was displayed on a a single arc in a path. I believe this bug has been captured by [this issue](https://bugs.chromium.org/p/chromium/issues/detail?id=583097). Chrome was rendering the SVG correctly, while `~/project/node_modules/puppeteer/.local-chromium/mac-737027/chrome-mac/Chromium.app` was not. It turned out that the fix has been merged into the Chromium that ships with [puppeteer 3.0.0](https://github.com/puppeteer/puppeteer/releases/tag/v3.0.0). My current workaround is just adding `"puppeteer": "^3.0.0"` directly to my dependencies but naturally I would prefer an upstream fix. Thank you! 🙂

**Comment by shakiba** [comment]
Thanks for reporting the issue with a fix! It would be great if you make a PR.

**Comment by KasparEtter** [comment]
Here you go. I haven't studied what the breaking changes in [puppeteer 3.0.0](https://github.com/puppeteer/puppeteer/releases/tag/v3.0.0) were but since it includes things like `Node.js v8.x.x is no longer supported.`, `svgexport` with these updated dependencies should probably be released with a major version bump.

**Comment by KasparEtter** [comment]
On a different note: I also wanted to commit the `package-lock.json` file (see [its documentation](https://docs.npmjs.com/files/package-lock.json) for why) but failed to actually install puppeteer because [it's currently not working with `node` 14](https://github.com/puppeteer/puppeteer/issues/5719). I'm too lazy to downgrade my `node` installation and the issue should be fixed with the 14.1.0 release.

**Comment by shakiba** [comment]
Thank, this is great! Will merge it soon, I think we can merge it as alpha version for next minor version update. Also let's cc @MichaelHeerklotz to see if he has any comment.

**Comment by KasparEtter** [comment]
Since [`node@14.1.0`](https://github.com/nodejs/node/releases/tag/v14.1.0) has been released in the meantime (and thus installing `puppeteer` works again), I added another commit to my PR in order to put `package-lock.json` under revision control. Otherwise, different developers can run into different issues due to differing versions of dependencies (as the dependencies are not "locked" to specific versions in the `package.json` file).
