### ISSUE TITLE
Not converting transform attributes

### ISSUE THREAD

**Issue by Kurtz1993** [shakiba/svgexport#8]
I tried to convert an SVG file with transform scale() and transform rotate(), but I can't get it to work. The conversion only outputs the images at their original coordinates but without any rotation or scale.

These are the properties that are not being converted:
style="transform: scale(1.9939797114561713) rotate(15.47907791300374925deg); transform-origin: 73.56616973876953px 56.75px;"

**Comment by shakiba** [comment]
svgexport uses phantomjs for rendering svg, please report to [phantomjs](https://github.com/ariya/phantomjs) instead.
