### ISSUE TITLE
Sizing issues when using %

### ISSUE THREAD

**Issue by Frozenfire92** [shakiba/svgexport#9]
This is related to #3 

I was having a similar issue where whenever I resized my svgs the output was always blank. I then compared my SVG (generated by [d3.js](http://d3js.org/)) to the one in #3 and the difference was my width/height were 100% where his was specified in pixels. I then changed my width/height to match my viewport size in pixels and it scaled perfectly.

**Comment by shakiba** [comment]
I'm not sure if using % in width/height is supported by phantomjs or even svg, see [here](https://wiki.mozilla.org/SVG:Sizing). Anyway currently svgexport does not read these values directly, instead it reads computed values from phantomjs.

**Comment by Frozenfire92** [comment]
I think the % is injected from stylesheets in a browser. I got that from copying from chrome's inspector.

When I copied the d3 from javascript it worked. Just something to note incase anyone else comes across this

**Comment by shakiba** [comment]
I see, thanks for sharing it.
