### ISSUE TITLE
Publish a new release of svgexport to npm

### ISSUE THREAD

**Issue by manuelroth** [shakiba/svgexport#96]
Dear @shakiba

I created a [PR](https://github.com/shakiba/svgexport/pull/90) that improves font spacing in docker environments. @MichaelRoosz reviewed and merged the PR. Would it be possible to push a new release to npm?- This would allow me to use the official svgexport package again in my package.json. Currently I have to use my feature-branch that I created for this PR.

Kind regards,
Manuel

**Comment by ancestral** [comment]
@shakiba I use this utility quite a lot. Can you publish a new release? If you need help maintaining the project, perhaps someone else can assist you.

I’m becoming afraid that if people don't hear from you, the project may end up being forked, leading people to transition away to a new project.

**Comment by shakiba** [comment]
Thanks for the PR! I published new version.

This kind of changes could be opinionated and it is difficult to know how they will impact existing users.

Any help with maintaining the project is definitely appreciated! :)

**Comment by manuelroth** [comment]
Thank you for publishing a new version. I really appreciate you taking the time. Yes, you are right. This change could have potential unwanted impact on existing users. Maybe an option to pass additional arguments to puppeteer would be a better solution to handle these use cases. I will close this issue as its resolved.
