### ISSUE TITLE
Support for decimal numbers in viewBox

### ISSUE THREAD

**Issue by mattsrinc** [shakiba/svgexport#98]
Hi, I would like to have a really simple improvement for this great library - **respecting decimal number in the input viewBox parameter**. A test to show the difference:

```
> svgexport test.svg test.png 1589:0:2213.4:2213.4 pad 256:256
(path)/test.svg (path)/test.png png 100% 0.05784055939488763x -623.73:0:4425.95:4425.95 256:256

> svgexport test.svg test.png 1589:0:2213:2213 pad 256:256
(path)/test.svg (path)/test.png png 100% 0.11568007230004519x 1589:0:2213:2213 256:256
```

So the first call with decimal numbers just rejects them and uses the original viewBox in the SVG file. The second call with integers works fine but does a side effect for tile image generation.

The story behind is that I would like to use svgexport for creating _Leaflet map tile images_. If calculated SVG image dimension division (by power of 2 numbers) - that gives a decimal number for image part to save to tile image dimensions as above - would be honored in svgexport viewBox parameter then the tiles (I guess) would perfectly zoom in and out.

Since only integers are valid in viewBox the map tiles get shifted causing shifting images when zoom level is changed. You can imagine unpleasant zooming experience, demonstrated in this image (cannot share the live URL):

![Screen Shot 2021-04-06 at 00 49 45](https://user-images.githubusercontent.com/7528073/113636302-91b61700-9672-11eb-84ee-83d5a092ac40.png)

For the completeness there is one [PHP script that creates map tiles from the large PNG image](https://github.com/Fedik/php-maptiler) but the quality of those map tiles just cannot be compared with svgexport output (I have created a Node.js app for creating map tiles).

BTW please don't answer with why the original SVG image doesn't have width and height (viewBox) attributes a power of 2 numbers (e.g. 512x1024, 2048x2048, you get the idea). That would solve the issue for sure - map tiles would be perfect (standard) 256x256 pixels 1:1 conversion. But we all know that maps are not like that. And that changing viewBox dimensions to have power of 2 square size (I do in the app for the square virtual size but only for matching greater width or height) would be silly for a lot of maps (they would have a lot of empty space - that could be somehow handled with proper initial zoom level).

**Comment by mattsrinc** [comment]
Is this the part in the render.js Command function that could be changed (regex to support float numbers and changing parsing calls below to parseFloat):

[https://github.com/shakiba/svgexport/blob/0cd3dab8c8fddf107b1e7a17be024f2462d30ebb/render.js#L245](https://github.com/shakiba/svgexport/blob/0cd3dab8c8fddf107b1e7a17be024f2462d30ebb/render.js#L245)

**Comment by mattsrinc** [comment]
Any help about this?

I'm attaching my modified version of render.js that unfortunately exports images as above.

Would really love to get this solved.

[render.js.zip](https://github.com/shakiba/svgexport/files/6292360/render.js.zip)

**Comment by mattsrinc** [comment]
For anyone doing similar task (exporting SVG to PNG tile images for Leafleat maps) here's the changed render.js for svgexport 0.3.2. It adds floating numbers support for the viewBox parameter (and width and height) and works well, with no artifacts when zooming as demonstrated in first image above.

Now if only svgexport 0.4 (or 0.5?) would have this it would be perfect.
[render.js-0.3.2-floatiing-numbers-viewBox.zip](https://github.com/shakiba/svgexport/files/6306862/render.js-0.3.2-floatiing-numbers-viewBox.zip)

**Comment by yisibl** [comment]
Try https://github.com/yisibl/resvg-js

**Comment by mattsrinc** [comment]
Resvg-js looks promising (have anyone tried with similar expected results e.g. SVG viewbox with floating numbers exported to PNG with integer dimensions?).

But I've solved what's needed with modifications above, hope they'll get merged to main svgexport.code.
